### ISSUE TITLE
Exception on parsing ImageMagick-7.0.8-68

### ISSUE THREAD

**Issue by fabsx00** [ShiftLeftSecurity/fuzzyc2cpg#132]
For ImageMagick at:
https://github.com/ImageMagick/ImageMagick/releases,
we get the following stacktrace:

```
➜  joern git:(master) ✗ time ./joern-parse targets/ImageMagick-7.0.8-68/
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/fabs/git/shiftleft/joern/joern-cli/target/universal/stage/lib/org.slf4j.slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/fabs/git/shiftleft/joern/joern-cli/target/universal/stage/lib/org.apache.logging.log4j.log4j-slf4j-impl-2.11.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[scala-execution-context-global-13] INFO io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label error.
[scala-execution-context-global-13] INFO io.shiftleft.fuzzyc2cpg.cfg.AstToCfgConverter$ - Unable to wire goto statement. Missing label error.
[scala-execution-context-global-11] INFO io.shiftleft.fuzzyc2cpg.parser.ModuleFunctionParserInterface - DisplayImageCommand was skipped.
[scala-execution-context-global-11] INFO io.shiftleft.fuzzyc2cpg.parser.ModuleFunctionParserInterface - CompositeImage was skipped.
Exception in thread "main" java.lang.StackOverflowError
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1496)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1496)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1496)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
	at org.antlr...
```

**Comment by GlassAndOneHalf** [comment]
This seems to originate from the file:
`../External/ImageMagick/tests/wandtest.c`

5500 lines long.. eep.

**Comment by GlassAndOneHalf** [comment]
Ok, so this issue is being caused by the _huuuuuge_ array defined inside `../External/ImageMagick/tests/wandtest.` from line 80 to line 5162.

**Comment by GlassAndOneHalf** [comment]
Further update - this only happens when parsing these large arrays from within a function.

**Comment by GlassAndOneHalf** [comment]
I'm having some difficulty fixing this with changes to the Grammar. I found this issue which seems to imply that it is a bug with Antlr4: https://github.com/antlr/antlr4/issues/1943
