### ISSUE TITLE
MatchError when parsing Microsoft Terminal

### ISSUE THREAD

**Issue by GlassAndOneHalf** [ShiftLeftSecurity/fuzzyc2cpg#158]
A `MatchError` is raised when parsing the [Microsoft Terminal](https://github.com/microsoft/terminal) project:

```
[scala-execution-context-global-21] WARN io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg - Cannot parse module: terminal/src/host/ut_host/TextBufferTests.cpp, skipping
[scala-execution-context-global-21] WARN io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg - Complete exception: 
scala.MatchError:   (of class java.lang.String)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.visit(AstToCpgConverter.scala:305)
	at io.shiftleft.fuzzyc2cpg.ast.walking.ASTNodeVisitor.visit(ASTNodeVisitor.java:290)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.visit(AstToCpgConverter.scala:28)
	at io.shiftleft.fuzzyc2cpg.ast.expressions.UnaryOperationExpression.accept(UnaryOperationExpression.java:8)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.visitBinaryExpr(AstToCpgConverter.scala:755)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.visit(AstToCpgConverter.scala:231)
	at io.shiftleft.fuzzyc2cpg.ast.expressions.AssignmentExpression.accept(AssignmentExpression.java:8)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.visit(AstToCpgConverter.scala:615)
	at io.shiftleft.fuzzyc2cpg.ast.declarations.IdentifierDecl.accept(IdentifierDecl.java:62)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.$anonfun$visit$9(AstToCpgConverter.scala:567)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.$anonfun$visit$9$adapted(AstToCpgConverter.scala:566)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.visit(AstToCpgConverter.scala:566)
	at io.shiftleft.fuzzyc2cpg.ast.statements.IdentifierDeclStatement.accept(IdentifierDeclStatement.java:34)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.$anonfun$visit$7(AstToCpgConverter.scala:545)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.$anonfun$visit$7$adapted(AstToCpgConverter.scala:544)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.visit(AstToCpgConverter.scala:544)
	at io.shiftleft.fuzzyc2cpg.ast.logical.statements.CompoundStatement.accept(CompoundStatement.java:39)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.visit(AstToCpgConverter.scala:176)
	at io.shiftleft.fuzzyc2cpg.ast.walking.ASTNodeVisitor.visit(ASTNodeVisitor.java:326)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.visit(AstToCpgConverter.scala:28)
	at io.shiftleft.fuzzyc2cpg.ast.langc.functiondef.FunctionDef.accept(FunctionDef.java:59)
	at io.shiftleft.fuzzyc2cpg.astnew.AstToCpgConverter.convert(AstToCpgConverter.scala:114)
	at io.shiftleft.fuzzyc2cpg.AstVisitor.visit(AstVisitor.scala:37)
	at io.shiftleft.fuzzyc2cpg.ast.langc.functiondef.FunctionDef.accept(FunctionDef.java:59)
	at io.shiftleft.fuzzyc2cpg.AstVisitor.processItem(AstVisitor.scala:86)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver$3.accept(AntlrParserDriver.java:267)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver$3.accept(AntlrParserDriver.java:264)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.notifyObservers(AntlrParserDriver.java:224)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.notifyObserversOfItem(AntlrParserDriver.java:264)
	at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.exitFunction_def(CModuleParserTreeListener.java:85)
	at io.shiftleft.fuzzyc2cpg.ModuleParser$Function_defContext.exitRule(ModuleParser.java:547)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.walkTree(AntlrParserDriver.java:177)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.parseAndWalkFile(AntlrParserDriver.java:78)
	at io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg.createCpgForCompilationUnit(FuzzyC2Cpg.scala:173)
	at io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg.$anonfun$runAndOutput$1(FuzzyC2Cpg.scala:87)
	at io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg.$anonfun$runAndOutput$1$adapted(FuzzyC2Cpg.scala:87)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.parallel.immutable.ParHashSet$ParHashSetIterator.foreach(ParHashSet.scala:81)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by GlassAndOneHalf** [comment]
Can reproduce with this code snippet:
```
void main() {
  // This is the peach emoji: 🍑
  const auto derefed = *ref;
}
```

Note that this crash only occurs from within a function.

**Comment by GlassAndOneHalf** [comment]
Fixed by https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/164
