### ISSUE TITLE
EmptyStackException when parsing Tensorflow

### ISSUE THREAD

**Issue by GlassAndOneHalf** [ShiftLeftSecurity/fuzzyc2cpg#159]
An `EmptyStackException` is raised when parsing the [Tensorflow](https://github.com/tensorflow/tensorflow) project. Looks related to templates:

```
[scala-execution-context-global-28] WARN io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg - Cannot parse module: tensorflow/tensorflow/compiler/xla/literal.h, skipping
[scala-execution-context-global-28] WARN io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg - Complete exception: 
java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.enterTemplate_decl(CModuleParserTreeListener.java:115)
	at io.shiftleft.fuzzyc2cpg.ModuleParser$Template_declContext.enterRule(ModuleParser.java:3660)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:42)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:25)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.walkTree(AntlrParserDriver.java:177)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.parseAndWalkTokenStream(AntlrParserDriver.java:123)
	at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.parseClassContent(CModuleParserTreeListener.java:205)
	at io.shiftleft.fuzzyc2cpg.parser.modules.CModuleParserTreeListener.exitDeclByClass(CModuleParserTreeListener.java:168)
	at io.shiftleft.fuzzyc2cpg.ModuleParser$DeclByClassContext.exitRule(ModuleParser.java:2322)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.walkTree(AntlrParserDriver.java:177)
	at io.shiftleft.fuzzyc2cpg.parser.AntlrParserDriver.parseAndWalkFile(AntlrParserDriver.java:78)
	at io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg.createCpgForCompilationUnit(FuzzyC2Cpg.scala:173)
	at io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg.$anonfun$runAndOutput$1(FuzzyC2Cpg.scala:87)
	at io.shiftleft.fuzzyc2cpg.FuzzyC2Cpg.$anonfun$runAndOutput$1$adapted(FuzzyC2Cpg.scala:87)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.parallel.immutable.ParHashSet$ParHashSetIterator.foreach(ParHashSet.scala:81)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:170)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by GlassAndOneHalf** [comment]
Checked and fixed by https://github.com/ShiftLeftSecurity/fuzzyc2cpg/pull/163
